name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'master'
        type: string

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Build
        run: xcodebuild -scheme Stats -destination 'platform=macOS' -configuration Release archive -archivePath ./Stats.xcarchive CODE_SIGNING_ALLOWED=NO

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Stats-${{ github.sha }}
          path: ./Stats.xcarchive/Products/Applications/Stats.app
